export const HIDDEN_SLIDE_IDS = new Set<string>([
  "page0",
  "page14",
  "page15",
  "page16",
  "page17",
  "page18",
  "page19",
  "page20",
  "video-entry-experience",
  "video-async-loop",
  "page31",
  "page9",
  "page29",
  "page30",
])

export const allSlideIds = [
  "cover",
  "content0",
  "page0a",
  "page0b",
  "page0c",
  "page0d",
  "page0e",
  "page0f",
  "page0g",
  "page4b",
  "page27",
  "video-user-journey",
  "video-recommendation-upload",
  "video-concurrent-tasks",
  "video-context-system",
  "video-template-remix",
  "video-entry-experience",
  "video-async-loop",
  "page31",
  "page28",
  "page29",
  "page30",
  "video-future",
  "page32",
  "page0",
  "page1",
  "page2",
  "page3",
  "page4",
  "page5",
  "page6",
  "page7",
  "page8",
  "page9",
  "page10",
  "page11",
  "page12",
  "page13",
  "ai-platform-overview",
  "page14",
  "page15",
  "page16",
  "page17",
  "page18",
  "page19",
  "page20",
  "page21",
  "page22",
  "if-studio",
  "if-studio-capabilities",
  "other-creative-projects",
  "other-agent-projects",
  "other-search-projects",
] as const

export const VISIBLE_SLIDE_COUNT = allSlideIds.filter(
  (id) => !HIDDEN_SLIDE_IDS.has(id)
).length
